[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm>=6.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.1"

[tool.black]
line-length = 79
quiet = true
