FROM fedora:34

RUN yum install \
    -y --setopt=install_weak_deps=False \
    git \
    mercurial \
    python-pip \
    python-pip-wheel \
    python-setuptools \
    python-setuptools-wheel \
    python-tox \
    python3-samba \
    python3-wheel \
    python3-pyxattr \
    samba-common-tools \
    && yum clean all \
    && true
COPY build.sh /usr/local/bin/build.sh
ENTRYPOINT ["/usr/local/bin/build.sh"]
